config/routes.rb
Rails.application.routes.draw do

  get 'settings' => "settings#index"

  post 'settings' => "settings#reset"

  resources :brands, only: [:index, :new, :create, :destroy]

  resources :employees, only: [:index, :new, :create, :destroy]

  resources :sales, only: [:new, :create]

  resources :inventories, only: [:index, :new, :create]

  resources :reports, only: [:index]

  get 'reports/sales'

  get 'reports/sold'

  get "inventories/search" => "inventories#search"

  root "welcome#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :inventories
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :sales
  has_many :inventories, through: :sales
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :brand
  has_one :sale
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :employee
  belongs_to :inventory
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.all
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new
    @brand.name = params[:brand][:name]

    if @brand.save
      flash[:notice] = "\"#{@brand.name}\" has been added to Brands!"
      redirect_to brands_path
    else
      flash.now[:alert] = "There was an error adding the Brand. Please try again."
      render :new
    end
  end

  def destroy
    @brand = Brand.find(params[:id])

    if @brand.destroy
      flash[:notice] = "\"#{@brand.name}\" was deleted successfully."
      redirect_to brands_path
    else
      flash.now[:alert] = "There was an error deleting the brand."
      render brands_path
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new
    @employee.name = params[:employee][:name]

    if @employee.save
      flash[:notice] = "\"#{@employee.name}\" has been added!"
      redirect_to employees_path
    else
      flash.now[:alert] = "There was an error creating the Employee. Please try again."
      render :new
    end
  end

  def destroy
    @employee = Employee.find(params[:id])

    if @employee.destroy
      flash[:notice] = "\"#{@employee.name}\" was deleted successfully."
      redirect_to employees_path
    else
      flash.now[:alert] = "There was an error deleting the employee."
      render employees_path
    end
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)

    if @inventory.save
      flash[:notice] = "\"#{@inventory.style}\" has been added!"
      redirect_to inventories_path
    else
      flash.now[:alert] = "There was an error adding the item. Please try again."
      render :new
    end
  end

  def search
    if params[:search]
      @inventories = Inventory.where("style ILIKE ? OR category ILIKE ? OR size ILIKE ? OR color ILIKE ?", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
    else
      @inventories = [];
    end
  end

  private

  def inventory_params
    params.require(:inventory).permit(:style, :category, :brand_id, :price, :size, :color)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end

  def sales
    @sales = Sale.all
  end

  def sold
    @inventories = Inventory.where(available: false)
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def new
    @sale = Sale.new
    @inventories = Inventory.where(available: true)
    @employees = Employee.all
    @discount = 0

    if params[:id]
      @item = Inventory.find(params[:id])
      @sale.inventory_id = @item.id
    else
      @item = nil
    end

    if params[:discount]
      @discount = @item.price * (params[:discount].to_i / 100.to_f)
      @discounted_price = @item.price - @discount
      @total = @discounted_price * 1.12
      @sale.total = @total
    else
      @discount = 0
    end
  end

  def create
    @sale = Sale.new(sale_params)

    if @sale.save
      flash[:notice] = "Sale has been completed!"
      Inventory.update(@sale.inventory_id, :available => false)
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error completing the sale. Please try again."
      render :new
    end
  end

  private

  def sale_params
    params.require(:sale).permit(:total, :inventory_id, :employee_id)
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
  end

  def reset
    Brand.delete_all
    Employee.delete_all
    Inventory.delete_all
    Sale.delete_all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/inventorys_helper.rb
module InventorysHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/brands/index.html.erb
<h1 class="title">Brands</h1>
<div class="container centered">
  <% @brands.each do |brand| %>
    <div class="brand">
      <h4 class="brand-name"><%= brand.name %></h4>
      <%= link_to "Delete", brand_path(brand.id), method: :delete, class: "btn btn-danger brand-delete", data: { confirm: "Are you sure you would like to delete this Brand?" } %>
    </div>
  <% end %>
  <%= link_to "Add", new_brand_path, class: "btn btn-success add" %>
</div>

app/views/brands/new.html.erb
<h4>Add a Brand</h4>
<%= form_for @brand do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "sr-only" %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter Brand" %>
  </div>
  <%= f.submit "Add", class: "btn btn-success" %>
<% end %>

app/views/employees/index.html.erb
<h1 class="title">Employees</h1>
<div class="container centered">
  <% @employees.each do |emp| %>
    <div class="emp">
      <h4 class="emp-name"><%= emp.name %></h4>
      <%= link_to "Delete", employee_path(emp.id), method: :delete, class: "btn btn-danger emp-delete", data: { confirm: "Are you sure you would like to delete this employee?" } %>
    </div>
  <% end %>
  <%= link_to "Add", new_employee_path, class: "btn btn-success add" %>
</div>

app/views/employees/new.html.erb
<h4>Add an Employee</h4>
<%= form_for @employee do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "sr-only" %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter name" %>
  </div>
  <%= f.submit "Add", class: "btn btn-success" %>
<% end %>

app/views/inventories/index.html.erb
<h1 class="title">Inventory</h1>
<div class="container centered">
  <div>
    <%= link_to "SEARCH", inventories_search_path, class: "btn btn-info btn-lg" %>
  </div>
  <div>
    <%= link_to "ADD", new_inventory_path, class: "btn btn-info btn-lg" %>
  </div>
</div>

app/views/inventories/new.html.erb
<h4>Add an item</h4>
<%= form_for @inventory do |f| %>
  <div class="form-group">
    <%= f.label :brand_id, class: "sr-only" %>
    <%= f.collection_select :brand_id, Brand.all, :id, :name, include_blank: "Select Brand", class: "form-control", :required => true %>
  </div>
  <div class="form-group">
    <%= f.label :style, class: "sr-only" %>
    <%= f.text_field :style, class: "form-control", placeholder: "Enter Style Name", :required => true %>
  </div>
  <div class="form-group">
    <%= f.label :category, class: "sr-only" %>
    <%= f.text_field :category, class: "form-control", placeholder: "Enter Category", :required => true %>
  </div>
  <div class="form-group">
    <%= f.label :color, class: "sr-only" %>
    <%= f.text_field :color, class: "form-control", placeholder: "Enter Color", :required => true %>
  </div>
  <div class="form-group">
    <%= f.label :size, class: "sr-only" %>
    <%= f.text_field :size, class: "form-control", placeholder: "Enter Size", :required => true %>
  </div>
  <div class="form-group">
    <%= f.label :price, class: "sr-only" %>
    <%= f.number_field :price, step: :any, class: "form-control", placeholder: "Enter Price", :required => true %>
  </div>
  <%= f.submit "Add", class: "btn btn-success" %>
<% end %>

app/views/inventories/search.html.erb
<h4>Search Inventory</h4>
<%= form_for inventories_search_path, :method => "get" do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search" %>
  <%= submit_tag "SEARCH", :name => nil, class: "btn btn-success" %>
<% end %>

<table class="table table-striped table-bordered">
  <tr>
    <th>Brand</th>
    <th>Style</th>
    <th>Category</th>
    <th>Color</th>
    <th>Size</th>
    <th>Price($)</th>
    <th>Sold</th>
  </tr>
  <% @inventories.each do |item| %>
    <tr class="<%= 'sold' if item.available == false %>">
      <td><%= Brand.where(id: item.brand_id).first.name %></td>
      <td><%= item.style %></td>
      <td><%= item.category %></td>
      <td><%= item.color %></td>
      <td><%= item.size %></td>
      <td><%= number_to_currency(item.price) %></td>
      <td>
        <% if item.available == true %>
          Available
        <% else %>
          SOLD
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/reports/index.html.erb
<h1 class="title">Reports</h1>
<div class="container centered">
  <div>
    <%= link_to "SALES", reports_sales_path, class: "btn btn-info btn-lg" %>
  </div>
  <div>
    <%= link_to "ITEMS SOLD", reports_sold_path, class: "btn btn-info btn-lg" %>
  </div>
</div>

app/views/reports/sales.html.erb
<h1 class="title">SALES</h1>

<table class="table table-striped table-bordered">
  <tr>
    <th>Invoice #</th>
    <th>Total</th>
    <th>Employee</th>
    <th>Time</th>
  </tr>
  <% @sales.each do |s| %>
    <tr>
      <td><%= s.id %></td>
      <td><%= number_to_currency(s.total) %></td>
      <td><%= Employee.where(id: s.employee_id).first.name %></td>
      <td><%= s.created_at.strftime("%l:%M%p - %a, %b %d %Y") %></td>
    </tr>
  <% end %>
</table>

app/views/reports/sold.html.erb
<h1 class="title">ITEMS SOLD</h1>

<table class="table table-striped table-bordered">
  <tr>
    <th>Brand</th>
    <th>Style</th>
    <th>Category</th>
    <th>Color</th>
    <th>Size</th>
    <th>Price</th>
    <th>Sale Price</th>
  </tr>
  <% @inventories.each do |item| %>
    <tr>
      <td><%= Brand.where(id: item.brand_id).first.name %></td>
      <td><%= item.style %></td>
      <td><%= item.category %></td>
      <td><%= item.color %></td>
      <td><%= item.size %></td>
      <td><%= number_to_currency(item.price) %></td>
      <td><%= number_to_currency(Sale.where(inventory_id: item.id).first.total) %></td>
    </tr>
  <% end %>
</table>

app/views/sales/new.html.erb
<h1 class="title">NEW SALE</h1>
<div class="row">
  <div class="col-sm-4">
    <%= form_for new_sale_path, :method => "get" do %>
      <%= select_tag "id", options_from_collection_for_select(@inventories, :id, :style), prompt: "Select
      Item", :required => true %>
      <%= number_field_tag :discount, params[:discount], placeholder: "Discount (%)" %>
      <%= submit_tag "Add", :name => nil, class: "btn btn-success" %>
    <% end %>
  </div>
  <div class="col-sm-8">
    <table class="table table-bordered">
      <tr>
        <th>Brand</th>
        <th>Style</th>
        <th>Category</th>
        <th>Color</th>
        <th>Size</th>
        <th>Price</th>
      </tr>
      <tr>
        <% if @item %>
          <td><%= Brand.where(id: @item.brand_id).first.name %></td>
          <td><%= @item.style %></td>
          <td><%= @item.category %></td>
          <td><%= @item.color %></td>
          <td><%= @item.size %></td>
          <td><%= number_to_currency(@item.price) %></td>
        <% else %>
          <td>N/A</td>
          <td>N/A</td>
          <td>N/A</td>
          <td>N/A</td>
          <td>N/A</td>
          <td>$0</td>
        <% end %>
      </tr>
    </table>
    <table class="table table-bordered">
      <% if @item %>
        <tr>
          <td>Discount:</td>
          <td><%= number_to_currency(@discount) %></td>
        </tr>
        <tr>
          <td>Subtotal:</td>
          <td><%= number_to_currency(@discounted_price) %></td>
        </tr>
        <tr>
          <td>Tax:</td>
          <td><%= number_to_currency(@discounted_price * 0.12) %></td>
        </tr>
        <tr>
          <td class="red">Total:</td>
          <td class="red"><%= number_to_currency(@total) %></td>
        </tr>
      <% else %>
        <tr>
          <td>Discount:</td>
          <td>$0.00</td>
        </tr>
        <tr>
          <td>Subtotal:</td>
          <td>$0.00</td>
        </tr>
        <tr>
          <td>Tax:</td>
          <td>$0.00</td>
        </tr>
        <tr>
          <td class="red">Total:</td>
          <td class="red">$0.00</td>
        </tr>
      <% end %>
    </table>
  </div>
  <% if @item && @total %>
    <%= form_for @sale do |f| %>
      <div class="form-group">
        <%= f.label :employee_id, class: "sr-only" %>
        <%= f.collection_select :employee_id, @employees, :id, :name, include_blank: "Select Employee", class: "form-control", :required => true %>
          <%= f.hidden_field :inventory_id, :value => @item.id %>
          <%= f.hidden_field :total, :value => @total %>
      </div>
      <%= f.submit "Process", class: "btn btn-success" %>
    <% end %>
  <% end %>
</div>

app/views/settings/index.html.erb
<h1 class="title">CUEB POS</h1>
<div class="container centered">
  <div>
    <%= link_to "BRANDS", brands_path, class: "btn btn-info btn-lg" %>
  </div>
  <div>
    <%= link_to "EMPLOYEES", employees_path, class: "btn btn-info btn-lg" %>
  </div>
  <div>
    <%= link_to "RESET DATA", settings_path, method: :post, :data => {:confirm => 'Are you sure you would like to reset all data?'}, class: "btn btn-info btn-lg" %>
  </div>
</div>

app/views/welcome/index.html.erb
<h1 class="title">CUEB POS</h1>
<div class="container centered">
  <div>
    <%= link_to "SALES", new_sale_path, class: "btn btn-info btn-lg" %>
  </div>
  <div>
    <%= link_to "INVENTORY", inventories_path, class: "btn btn-info btn-lg" %>
  </div>
  <div>
    <%= link_to "REPORTS", reports_path, class: "btn btn-info btn-lg" %>
  </div>
  <div>
    <%= link_to "SETTINGS", settings_path, class: "btn btn-info btn-lg" %>
  </div>
</div>